name: PikoPluginLib
version: ${version}
main: ru.piko.pikopluginlib.Main
api-version: '1.21'
depend: [NBTAPI]
commands:
  piko:
    usage: /piko ...
permissions :
  piko.commands.admin:
    description: "admin commands"
    default: op
    children:
      piko.commands.admin.reload: true
